fix: imporve implcit qubit permutations warning
CQCL/pytket-qiskit pull request #421
Opened 2024-11-21 15:41 UTC by CalMacCQ

# Description

Please summarise the changes.

# Related issues

Please mention any github issues addressed by this PR.

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

2024-11-21 15:46 UTC, CalMacCQ commented on tests/qiskit_convert_test.py
> +    state_backend = AerStateBackend()
I wrote this test without the flag added to ensure that it failed. 

The warning only appears for `AerBackend` and not `AerStateBackend`. I would've expected both to generate a warning (i.e. `record` to be of length 2)

2024-11-21 16:05 UTC, CalMacCQ commented on tests/qiskit_convert_test.py
> +    state_backend = AerStateBackend()
Ah its because the state and unitary backends replace implicit swaps with SWAP gates whereas `AerBackend` does not.

2024-11-21 16:50 UTC, CalMacCQ commented on docs/index.md
> +:widths: 25 25 25 25
This fixes an error due to an invalid number of columns

2024-11-21 16:55 UTC, CalMacCQ commented
Sorry for commit spam. I think my linting settings were broken in my IDE.

2024-11-21 17:01 UTC, cqc-alec commented on pytket/extensions/qiskit/qiskit_convert.py
> +    :param perm_warnings: Warn if an input circuit has implicit qubit permutations,
```suggestion
    :param perm_warnings: Warn if an input circuit has implicit qubit permutations and `replace_implicit_swaps` is `False`,
```

2024-11-21 17:06 UTC, CalMacCQ commented on pytket/extensions/qiskit/qiskit_convert.py
> +    :param perm_warnings: Warn if an input circuit has implicit qubit permutations,
done [8bd887c](https://github.com/CQCL/pytket-qiskit/pull/421/commits/8bd887c213a71f422c8494903ac41e996cb81a95)

2024-11-21 17:06 UTC, CalMacCQ commented on pytket/extensions/qiskit/backends/aer.py
> +        perm_warning = False
Fair enough. Done [dd6e973](https://github.com/CQCL/pytket-qiskit/pull/421/commits/dd6e9733966fe87ed10da27fb947ebde2c1aad9f)

2024-11-22 09:12 UTC, cqc-alec requested changes

2024-11-22 09:12 UTC, cqc-alec commented on docs/changelog.md
> +- Fix an unhelpful warning message about implicit swaps when using optimisation level 2 with {py:class}`AerBackend`
OK

2024-11-22 09:12 UTC, cqc-alec commented on docs/changelog.md
> +- Add a boolean `perm_warn` argument to {py:func}`tk_to_qiskit` indicating whether to give a warning if the input {py:class}`Circuit` has an implicit qubit permutation.
```suggestion
- Add a boolean `perm_warning` argument to {py:func}`tk_to_qiskit` indicating whether to give a warning if the input {py:class}`Circuit` has an implicit qubit permutation.
```

2024-11-22 09:12 UTC, cqc-alec commented on pytket/extensions/qiskit/qiskit_convert.py
> +    :param perm_warnings: Warn if an input circuit has implicit qubit permutations,
```suggestion
    :param perm_warning: Warn if an input circuit has implicit qubit permutations,
```

2024-11-22 13:55 UTC, cqc-alec approved these changes

2024-11-22 13:58 UTC, merged